### ISSUE TITLE
IDLE problem: The script terminated while IMAP connection failure

### ISSUE THREAD

**Issue by xdnroot** [xdnroot/email-listener#1]
The first time, I tested this script, I use hawkhost.com as a mail server (IMAP server).

I got my script terminated when the IMAP server didn't respond or responds with a failed message.
```
22-05-2021 20:05:33 | imap_monitor | INFO | ... script started
22-05-2021 20:05:33 | imap_monitor | INFO | setting path for email downloads - /home/xdn/email-listener-api/monitor.py
22-05-2021 20:05:33 | imap_monitor | INFO | connecting to IMAP server - sng123.hawkhost.com
22-05-2021 20:05:34 | imap_monitor | INFO | server connection established
22-05-2021 20:05:34 | imap_monitor | INFO | logging in to IMAP server - test1@webiptek.com
22-05-2021 20:05:34 | imap_monitor | INFO | login successful - b'Logged in'
22-05-2021 20:05:34 | imap_monitor | INFO | selecting IMAP folder - INBOX
22-05-2021 20:05:34 | imap_monitor | INFO | folder selected
22-05-2021 20:05:34 | imap_monitor | WARNING | 0 unread messages seen - []
22-05-2021 20:05:50 | imap_monitor | WARNING | 0 new unread messages - []
22-05-2021 20:10:50 | imap_monitor | WARNING | no new messages seen
22-05-2021 20:15:50 | imap_monitor | WARNING | no new messages seen
22-05-2021 20:20:50 | imap_monitor | WARNING | no new messages seen
22-05-2021 20:25:50 | imap_monitor | WARNING | no new messages seen
22-05-2021 20:29:50 | imap_monitor | WARNING | 0 new unread messages - []
22-05-2021 20:34:50 | imap_monitor | WARNING | no new messages seen
22-05-2021 20:39:50 | imap_monitor | WARNING | no new messages seen
Traceback (most recent call last):
  File "monitor.py", line 239, in <module>
    main()
  File "monitor.py", line 225, in main
    imap.idle_done()
  File "/home/xdn/email-listener-api/venv/lib/python3.8/site-packages/imapclient/imapclient.py", line 175, in wrapper
    return func(client, *args, **kwargs)
  File "/home/xdn/email-listener-api/venv/lib/python3.8/site-packages/imapclient/imapclient.py", line 975, in idle_done
    return self._consume_until_tagged_response(self._idle_tag, "IDLE")
  File "/home/xdn/email-listener-api/venv/lib/python3.8/site-packages/imapclient/imapclient.py", line 1596, in _consume_until_tagged_response
    line = self._imap._get_response()
  File "/usr/lib/python3.8/imaplib.py", line 1050, in _get_response
    resp = self._get_line()
  File "/usr/lib/python3.8/imaplib.py", line 1160, in _get_line
    raise self.abort('socket error: EOF')
imaplib.abort: socket error: EOF
```

How do I know this error caused by an unstable IMAP server? Because in my second testing, I used imap.gmail.com, and my script not terminated because (I think) the Google IMAP server is stable than Hawkhost server.

I was trying to fix it as I can, but I couldn't fix it yet.

**Comment by xdnroot** [comment]
Use process manager to restart the script when a failure occurs, automatically.
Read the docs: [https://pm2.keymetrics.io/docs/usage/pm2-doc-single-page](https://pm2.keymetrics.io/docs/usage/pm2-doc-single-page)
